# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('time', models.TimeField(verbose_name='时间')),
                ('photograph', models.CharField(max_length=100, verbose_name='图片')),
                ('license_plate', models.CharField(max_length=100, verbose_name='车牌号')),
                ('type', models.CharField(max_length=10, verbose_name='车型')),
                ('state', models.BooleanField(default=False, verbose_name='状态')),
                ('price', models.FloatField(blank=True, default=-1, verbose_name='收费')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='UserPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('license_plate', models.CharField(max_length=100, verbose_name='车牌号')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
