# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20191008_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='price',
            field=models.FloatField(blank=True, default=0.0, verbose_name='收费'),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
