# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20191008_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20, verbose_name='地区')),
                ('provinces', models.CharField(max_length=100, verbose_name='省份')),
                ('day_time_price', models.FloatField(blank=True, default=0.0, verbose_name='日间价格')),
                ('night_time_price', models.FloatField(blank=True, default=0.0, verbose_name='夜间价格')),
            ],
            options={
                'ordering': ['-area'],
            },
        ),
    ]
