# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_pricestandard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricestandard',
            name='first_hour_price',
            field=models.FloatField(blank=True, default=0.0, verbose_name='首小时价格'),
        ),
    ]
